PHP changes for mirroring

diff --git a/usr/local/sbin/mirror-cd-to-ogg b/usr/local/sbin/mirror-cd-to-ogg
--- a/usr/local/sbin/mirror-cd-to-ogg
+++ b/usr/local/sbin/mirror-cd-to-ogg
@@ -29,16 +29,14 @@
 
 # Mirror specified FLAC directory to ogg
 
-if [ $# -ne 1 ]
-then
-    echo "Usage: mirror-cd-to-ogg flacdir"
-    exit 1
+if [ $# -ne 1 ]; then
+  echo "Usage: mirror-cd-to-ogg flacdir"
+  exit 1
 fi
 
-if [ ! -d "$1" ]
-then
-    echo "Error: $1 is not a directory"
-    exit 2
+if [ ! -d "$1" ]; then
+  echo "Error: $1 is not a directory"
+  exit 2
 fi
 
 echo "/usr/local/sbin/mirror-cd-to-ogg $1"
@@ -46,39 +44,39 @@ echo "/usr/local/sbin/mirror-cd-to-ogg $1"
 flacdir="$1"
 oggdir=`echo $flacdir | sed -e "s;/flac/;/ogg/;" -`
 
-echo "FLAC dir is $flacdir"
-echo "Ogg dir is $oggdir"
+#echo "FLAC dir is $flacdir"
+#echo "Ogg dir is $oggdir"
 
 # Get cover art for FLAC dir
 
 echo "Getting cover art for $flacdir"
 if [ ! -f "$flacdir/cover.jpg" ]
 then
-    /opt/vortexbox/covergrabber.php "$flacdir"
+	/opt/vortexbox/covergrabber.php "$flacdir"
 fi
 
 if [ -f "$flacdir/cover.jpg" ]
 then
-   echo "copying $flacdir/cover.jpg to $flacdir/folder.jpg"
-   cp -a "$flacdir/cover.jpg" "$flacdir/folder.jpg"
+	echo "copying $flacdir/cover.jpg to $flacdir/folder.jpg"
+	cp -a "$flacdir/cover.jpg" "$flacdir/folder.jpg"
 fi
 
 echo "Mirroring FLAC files in $flacdir to ogg in $oggdir"
 
 if [ ! -d "$oggdir" ]
 then
-    mkdir -p "$oggdir"
+	mkdir -p "$oggdir"
 fi
 if [ -f "$flacdir/cover.jpg" ]
 then
-    cp -a "$flacdir/cover.jpg" "$oggdir/cover.jpg"
-    cp -a "$oggdir/cover.jpg" "$oggdir/folder.jpg"
+  cp -a "$flacdir/cover.jpg" "$oggdir/cover.jpg"
+  cp -a "$oggdir/cover.jpg" "$oggdir/folder.jpg"
 fi
 
-OGGOPT="`cat /etc/vortexbox/oggopt.txt` -o"
+oggopt="`cat /etc/vortexbox/oggopt.txt` -o"
 
 echo "$(/bin/date): Mirror of FLAC files in $flacdir to Ogg in $oggdir started."
 
-/usr/local/sbin/flac2ogg.sh "$flacdir $OGGOPT $oggdir"
+/usr/local/sbin/flac2ogg.sh "$flacdir" "$oggopt" "$oggdir"
 
 echo "$(/bin/date): Mirror of FLAC files in $flacdir to Ogg in $oggdir completed."
